class PermissionTable:
    can_make_admin = "can_make_admin"
    can_remove_admin = "can_remove_admin"
    can_make_lead = "can_make_lead"
    can_remove_lead = "can_remove_lead"
    can_invite_to_org = "can_invite_to_org"
    can_remove_from_org = "can_remove_from_org"
    can_add_team_user = "can_add_team_user"
    can_remove_team_user = "can_remove_team_user"
    can_manage_billing = "can_manage_billing"
    can_manage_model_deployment = "can_manage_model_deployment"
    can_manage_project = "can_manage_project"
    can_configure_connector = "can_configure_connector"
    can_modify_project_member = "can_modify_project_member"
    can_assign_project_write_access = "can_assign_project_write_access"
    can_modify_data_configuration_personnel = "can_modify_data_configuration_personnel"
    can_modify_project_resource = "can_modify_project_resource"
    can_create_team = "can_create_team"
